### ISSUE TITLE
Connection Timed Out Too fast.

### ISSUE THREAD

**Issue by KostyaTheSon** [DavidBuchanan314/fusee-nano#7]
Hi. I have a problem that indicates that the connection was timed out. It was unexpectedly fast. I think that the maximum timeout should be 1 minute. Could you fix the issue?

Signed
                - Kostya

**Comment by DavidBuchanan314** [comment]
Can you elaborate on why you believe the current timeout is insufficient? What is the actual problem you are experiencing?

**Comment by DavidBuchanan314** [comment]
Closed due to inactivity

**Comment by KostyaTheSon** [comment]
Okay. I knew it's my own Nintendo Switch. it's v2 Mariko... without any hardmod!!!!
